[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x1429ac83aed4a1468d979fe86ab8a1f453d7d10749006ef55155add8319fcede'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
